module.exports = {
  'pure-white': '#ffffff',
  'warm-white': '#f9f6da',
  'polar-white': '#feeaca',
  'soft-white': '#fbf5ea',
  'antique-white': '#faf6ea',
  'incandescent-white': '#f6e89f',
  'gold': '#f9c718',
  'red': '#ff0000',
  'orange': '#ffb000',
  'golden-yellow': '#ffcf00',
  'acid-yellow': '#beec05',
  'chartreuse': '#77fe00',
  'green': '#00ff00',
  'mint': '#00ff9c',
  'turquoise': '#00e0ff',
  'blue': '#009cff',
  'royal-blue': '#0000ff',
  'lavender': '#ab46fa',
  'pink': '#c400ff',
  'fushia': '#da14d2',
  'purple': '#9600ff'
}
